Repository salute-developers/plasma-android, pull requests merged in 2025-07, with the labels that each got.

#469 PLASMA-5216: uikit documentation
  sdds-core/uikit/docs/AvatarGroupUsage.md
  sdds-core/uikit/docs/AvatarUsage.md
  sdds-core/uikit/docs/BadgeUsage.md
  sdds-core/uikit/docs/ButtonUsage.md
  sdds-core/uikit/docs/CardUsage.md
  sdds-core/uikit/docs/CellUsage.md
  sdds-core/uikit/docs/CheckBoxGroupUsage.md
  sdds-core/uikit/docs/CheckBoxUsage.md
  sdds-core/uikit/docs/ChipGroupUsage.md
  sdds-core/uikit/docs/ChipUsage.md
  sdds-core/uikit/docs/CircularProgressBarUsage.md
  sdds-core/uikit/docs/CounterUsage.md
  sdds-core/uikit/docs/DividerUsage.md
  sdds-core/uikit/docs/DropDownMenuUsage.md
  sdds-core/uikit/docs/FlowUsage.md
  sdds-core/uikit/docs/FocusSelectorUsage.md
  sdds-core/uikit/docs/IndicatorUsage.md
  sdds-core/uikit/docs/ListItemUsage.md
  sdds-core/uikit/docs/ListUsage.md
  sdds-core/uikit/docs/ModalUsage.md
  sdds-core/uikit/docs/NavigationDrawerUsage.md
  sdds-core/uikit/docs/NotificationUsage.md
  sdds-core/uikit/docs/OverlayUsage.md
  sdds-core/uikit/docs/PopoverUsage.md
  sdds-core/uikit/docs/ProgressUsage.md
  sdds-core/uikit/docs/RadioBoxGroupUsage.md
  sdds-core/uikit/docs/RadioBoxUsage.md
  sdds-core/uikit/docs/RectSkeletonUsage.md
  sdds-core/uikit/docs/SegmentItemUsage.md
  sdds-core/uikit/docs/SegmentUsage.md
  sdds-core/uikit/docs/ShapeAppearance.md
  sdds-core/uikit/docs/SwitchUsage.md
  sdds-core/uikit/docs/TextFieldUsage.md
  sdds-core/uikit/docs/ToastUsage.md
  sdds-core/uikit/docs/TooltipUsage.md
Labels: documentation

#473 PLASMA-5233: Wheel.
  playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/vs/MenuItem.kt
  playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/wheel/vs/WheelFragment.kt
  playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/wheel/vs/WheelViewModel.kt
  playground/sandbox-compose/src/main/res/layout/layout_switch_property_item.xml
  playground/sandbox-compose/src/main/res/values/routes.xml
  playground/sandbox-core-integration/src/main/kotlin/com/sdds/playground/sandbox/core/integration/component/Component.kt
  playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/StarDsViewComponents.kt
  playground/sandbox-plasma-stards-integration/src/main/kotlin/com/sdds/playground/sandbox/plasma/stards/integration/wheel/StarDsWheelVariationsView.kt
  sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/ComponentDelegates.kt
  sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/WheelConfig.kt
  sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/WheelConfigDelegate.kt
  sdds-core/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/internal/components/wheel/view/WheelViewStyleGenerator.kt
  sdds-core/testing/src/main/kotlin/com/sdds/testing/vs/wheel/WheelFactory.kt
  sdds-core/testing/src/main/kotlin/com/sdds/testing/vs/wheel/WheelUiState.kt
  sdds-core/uikit/docs/WheelUsage.md
  sdds-core/uikit/src/main/kotlin/com/sdds/uikit/CellLayout.kt
  sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Divider.kt
  sdds-core/uikit/src/main/kotlin/com/sdds/uikit/Wheel.kt
  sdds-core/uikit/src/main/kotlin/com/sdds/uikit/drawable/DividerDrawable.kt
  sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/ItemEntrySelectedListener.kt
  sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/WheelItemView.kt
  sdds-core/uikit/src/main/kotlin/com/sdds/uikit/internal/wheel/WheelListView.kt
  sdds-core/uikit/src/main/res/layout/sd_layout_wheel_item.xml
  sdds-core/uikit/src/main/res/values/styles_wheel.xml
  sdds-core/uikit/src/main/res/values/wheel_attrs.xml
  tokens/plasma-stards-view/src/main/res/values/themes.xml
  tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_wheel_control_down_color.xml
  tokens/plasma-stards-view/src/main/theme-builder-res/color/sdkit_wheel_control_up_color.xml
  tokens/plasma-stards-view/src/main/theme-builder-res/values/style-dimens.xml
  tokens/plasma-stards-view/src/main/theme-builder-res/values/styles-wheel.xml
Labels: enhancement

#493 ci: Clean Docs on PR workflow was fixed.
  .github/workflows/clean-docs-pr.yml
Labels: bug

#494 ci: fix aws envs.
  .github/workflows/clean-docs-pr.yml
Labels: bug

#502 fix(sdds-acore/uikit-compose): AccordionItem iconColor was fixed. TextField chips radius was fixed
  build-system/gradle.properties
  gradle.properties
  playground/gradle.properties
  sdds-core/gradle.properties
  sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/AccordionItem.kt
  sdds-core/uikit-compose/src/main/kotlin/com/sdds/compose/uikit/internal/textfield/TextFieldLayout.kt
  tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemClearActionEndStyles.kt
  tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemClearActionStartStyles.kt
  tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
  tokens/plasma.giga.app.compose/src/main/kotlin/com/sdds/plasma/giga/app/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
  tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemClearActionEndStyles.kt
  tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemClearActionStartStyles.kt
  tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
  tokens/plasma.giga.compose/src/main/kotlin/com/sdds/plasma/giga/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
  tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemClearActionEndStyles.kt
  tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemClearActionStartStyles.kt
  tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
  tokens/plasma.sd.service.compose/src/main/kotlin/com/sdds/plasma/sd/service/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
  tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemClearActionEndStyles.kt
  tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemClearActionStartStyles.kt
  tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
  tokens/sdds.serv.compose/src/main/kotlin/com/sdds/serv/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
  tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemClearActionEndStyles.kt
  tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemClearActionStartStyles.kt
  tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemSolidActionEndStyles.kt
  tokens/stylessalute.compose/src/main/kotlin/com/sdds/stylessalute/styles/accordionitem/AccordionItemSolidActionStartStyles.kt
Labels: bug

#503 fix: Tokens documentation version history were fixed.
  .github/workflows/publish-sandbox-compose.yml
  build-system/conventions/src/main/kotlin/utils/DocsProjectUtils.kt
  playground/sandbox-compose/build.gradle.kts
  playground/sandbox-compose/src/main/kotlin/com/sdds/playground/sandbox/core/updates/UpdateChecker.kt
  tokens/plasma-stards-compose/override-docs/versionsArchived.json
  tokens/plasma-stards-view/override-docs/versionsArchived.json
  tokens/plasma.giga.app.compose/override-docs/versionsArchived.json
  tokens/plasma.giga.compose/override-docs/versionsArchived.json
  tokens/plasma.sd.service.compose/override-docs/versionsArchived.json
  tokens/plasma.sd.service.view/override-docs/versionsArchived.json
  tokens/sdds.serv.compose/override-docs/versionsArchived.json
  tokens/sdds.serv.view/override-docs/versionsArchived.json
  tokens/stylessalute.compose/override-docs/versionsArchived.json
  tokens/stylessalute.view/override-docs/versionsArchived.json
Labels: bug
